//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tmp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tmp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retreiving data. Check connection please.
        /// </summary>
        internal static string CheckConnection {
            get {
                return ResourceManager.GetString("CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Session.
        /// </summary>
        internal static string CloseSession {
            get {
                return ResourceManager.GetString("CloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the mail of your TMP account and follow the instructions of the mail you will receive.
        /// </summary>
        internal static string ConfirmLiteral {
            get {
                return ResourceManager.GetString("ConfirmLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPwd {
            get {
                return ResourceManager.GetString("ConfirmPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the current password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPwd {
            get {
                return ResourceManager.GetString("ForgotPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        internal static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont Have Account.
        /// </summary>
        internal static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must have at least 6 characters length.
        /// </summary>
        internal static string LengthPwd {
            get {
                return ResourceManager.GetString("LengthPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a new password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a new password confirm.
        /// </summary>
        internal static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Plan.
        /// </summary>
        internal static string NewPlan {
            get {
                return ResourceManager.GetString("NewPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        internal static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed.
        /// </summary>
        internal static string PwdChanged {
            get {
                return ResourceManager.GetString("PwdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was changed successfully.
        /// </summary>
        internal static string PwdChangedOk {
            get {
                return ResourceManager.GetString("PwdChangedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirm, does not match..
        /// </summary>
        internal static string PwdNotMatch {
            get {
                return ResourceManager.GetString("PwdNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill password recovery email received and new password.
        /// </summary>
        internal static string ReceivedCode {
            get {
                return ResourceManager.GetString("ReceivedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t send the new password to this email.
        /// </summary>
        internal static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the email you received and follow the instructions to create a new password.
        /// </summary>
        internal static string RecoveryMail {
            get {
                return ResourceManager.GetString("RecoveryMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a email.
        /// </summary>
        internal static string RegMailRequired {
            get {
                return ResourceManager.GetString("RegMailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email.
        /// </summary>
        internal static string RegMailValid {
            get {
                return ResourceManager.GetString("RegMailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE MARKETING PLANNER is an original idea and exclusive product of BRANDING SOUND SYSTEM. All rights reserved - 2019.
        /// </summary>
        internal static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option.
        /// </summary>
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Plan.
        /// </summary>
        internal static string SelectPlan {
            get {
                return ResourceManager.GetString("SelectPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if your product is a good or a service.
        /// </summary>
        internal static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not registered.
        /// </summary>
        internal static string ServerErrorLogin {
            get {
                return ResourceManager.GetString("ServerErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE MARKETING PLANNER.
        /// </summary>
        internal static string TmpSubtitle {
            get {
                return ResourceManager.GetString("TmpSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We send you an email.
        /// </summary>
        internal static string WeSend {
            get {
                return ResourceManager.GetString("WeSend", resourceCulture);
            }
        }
    }
}
